//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarmaWEBApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class absentdata
    {
        public int idAbsentData { get; set; }
        public string AbsentText { get; set; }
        public Nullable<System.DateTime> AbsentDate1 { get; set; }
        public Nullable<System.DateTime> AbsentDate2 { get; set; }
        public string PlayerID { get; set; }
    
        public virtual playerdata playerdata { get; set; }
    }
}
