//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarmaWEBApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chartable
    {
        public string charname { get; set; }
        public string idplayer { get; set; }
        public string char_role { get; set; }
        public string char_class { get; set; }
    
        public virtual class_list class_list { get; set; }
        public virtual playerdata playerdata { get; set; }
        public virtual roles_list roles_list { get; set; }
    }
}
