//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarmaWEBApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class raiddates
    {
        public int IdRaidValue { get; set; }
        public Nullable<int> RaidDate { get; set; }
        public string IDPlayer { get; set; }
        public Nullable<int> IDAttendance { get; set; }
        public Nullable<int> MinusAddition { get; set; }
        public Nullable<int> PlusAddition { get; set; }
        public Nullable<sbyte> IDIsActive { get; set; }

        public virtual string char_names
        {
            get
            {
            KarmaDBEntities db = new KarmaDBEntities();
            var DBRosterCharNames = db.chartable.Where(t => t.idplayer == IDPlayer);
            string CharacterString = "";
            foreach (var Character in DBRosterCharNames)
            {
                CharacterString = CharacterString + Character.charname + "(" + Character.char_class + "/" + Character.char_role + "),";
            }
            CharacterString = CharacterString.Substring(0, (CharacterString.Length - 1));
            return CharacterString;
            }
    }

        public virtual attendance_list attendance_list { get; set; }
        public virtual playerdata playerdata { get; set; }
    }
}
