//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarmaWEBApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class settingstable
    {
        public string idSetting { get; set; }
        public Nullable<int> ValueSetting { get; set; }
    }
}
